@startuml
!theme plain

title Блок-схема процесса оформления заявки у клиента

start

if (Авторизован ли клиент?) then (Нет)
  :Введите ФИО, номер телефона, почту;
  :Создать аккаунт;
else (Да)
endif
:Оформить новую заявку;
:Укажите количество вещей;
:Укажите степень загрязнения белья;
:Создать заявку;


  stop
@enduml