@startuml
!theme plain

title Блок-схема процесса оформления заявки у клиента

start

if (Авторизован ли клиент?) then (Нет)
  :Введите ФИО, номер телефона, почту;
  :Создать аккаунт;
else (Да)
endif
:Оформить новую заявку;
:Укажите количество вещей;
:Укажите степень загрязнения белья;

if (Есть ли удобное для вас время?) then (Нет)
  :К сожалению, это время занято,\n выберите другое;
else (Да)
  :Выбранное время свободно;
  :Создать заявку;

  endif

  stop
@enduml