@startuml
!theme plain
title Блок-схема процесса оформления заявки у админа
start
:Вывести данные о клиенте;
if (Клиент подтверждает бронь?) then (Да)
  :Подтверждение брони;
  :Статус заявки: ожидает оплаты;
else (Нет)
  :Отмена брони;
  :Статус заявки: отклонена;
endif
stop
@enduml